services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:3000
    ports:
      - "8081:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - UI_URL=http://localhost:8081
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
