version: '3.8'

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - UI_URL=${UI_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
