version: '3.8'

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    depends_on:
      - api
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - UI_URL=${UI_URL:-http://localhost:8081}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
